# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: es-prestamo
replicaCount: 1
type: api
project: es-prestamo
releaseId: ""
environment: "cert"

image:
  repository: "acrenvironmicrostrv001.azurecr.io/prdfldrimgapi"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: es-prestamo-v1.0.0
  
settingSecrets: 
  enabled: false

readinessProbe:
  httpGet:
    path: /q/health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

podAnnotations: {}

podSecurityContext: 
  runAsUser: 10001
  runAsGroup: 10001

securityContext:
  readOnlyRootFilesystem: false
  
service:
  type: ClusterIP
  port: 80
  internalEnabled: true
  ip:

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.org/client-max-body-size: 20m
    nginx.org/proxy-connect-timeout: 600s
    nginx.org/proxy-read-timeout: 600s
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS, PUT, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,access-control-allow-origin,Authorization"
  hosts:
    path: /v1/es/prestamo-fic
    pathType: Prefix
    host: cer.pdnsz-micros-trv.private
    
resources:
  limits:
    cpu: 300m
    memory: 512Mi
    ephemeral-storage: "512Mi"
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: "64Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  threshold: 20

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}