# Default values for api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: es-prestamo
replicaCount: 1
type: api
project: es-prestamo
releaseId: ""
environment: "cert"

image:
  repository: "acrenvironmicrostrv001.azurecr.io/cerfldrimgapi"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: es-prestamo-v1.0.0

logs:
  enabled: false
  
settingSecrets: 
  enabled: false

readinessProbe:
  httpGet:
    path: /q/health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10

podAnnotations: {}

podSecurityContext: 
  runAsUser: 10001
  runAsGroup: 10001

securityContext:
  readOnlyRootFilesystem: false
  
service:
  type: ClusterIP
  port: 80
  internalEnabled: true
  ip:

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
    nginx.org/client-max-body-size: 20m
  hosts:
    path: /v1/es/prestamo-fic
    pathType: Prefix
    host: priv-ingresscer.mibanco.com.co
    
resources:
  limits:
    cpu: 300m
    memory: 512Mi
    ephemeral-storage: "512Mi"
  requests:
    cpu: 100m
    memory: 128Mi
    ephemeral-storage: "64Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  threshold: 20

nodeSelector:
  kubernetes.io/os: linux

tolerations: []

affinity: {}
envs:
  - name: quarkus.rest-client.autenticacionMS.url
    value: http://ms-autenticar/v1/ms/acceso/verifica/usuario
  - name: "hostQuarkus"
    value: "us-gestorsecretost"
  - name: "puertoQuarkus"
    value: "80"
  - name: quarkus.http.port
    value: "8080"

  - name: usuarioDB
    valueFrom:
      secretKeyRef:
        name: es-prestamo
        key: usuarioDB

  - name: passwordDB
    valueFrom:
      secretKeyRef:
        name: es-prestamo
        key: passwordDB

  - name: nombreBaul
    valueFrom:
      secretKeyRef:
        name: es-prestamo
        key: nombreBaul

  - name: stringConexion
    valueFrom:
      secretKeyRef:
        name: es-prestamo
        key: stringConexion